// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{appName}\secretkeys\{secretName}\verify
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VerifyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VerifyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appName}/secretkeys/{secretName}/verify{?min_version*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VerifyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{appName}/secretkeys/{secretName}/verify{?min_version*}", rawUrl)
        {
        }
        /// <summary>
        /// Verify with a secret key
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.ErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::Soenneker.Fly.Machines.OpenApiClient.Models.VerifySecretkeyRequest body, Action<RequestConfiguration<global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder.VerifyRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::Soenneker.Fly.Machines.OpenApiClient.Models.VerifySecretkeyRequest body, Action<RequestConfiguration<global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder.VerifyRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Fly.Machines.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Verify with a secret key
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Fly.Machines.OpenApiClient.Models.VerifySecretkeyRequest body, Action<RequestConfiguration<global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder.VerifyRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Fly.Machines.OpenApiClient.Models.VerifySecretkeyRequest body, Action<RequestConfiguration<global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder.VerifyRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.Item.Verify.VerifyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Verify with a secret key
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VerifyRequestBuilderPostQueryParameters 
        {
            /// <summary>Minimum secrets version to return. Returned when setting a new secret</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("min_version")]
            public string? MinVersion { get; set; }
#nullable restore
#else
            [QueryParameter("min_version")]
            public string MinVersion { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
