// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Machines;
using Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Volumes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Orgs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{orgSlug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrgSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The machines property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Machines.MachinesRequestBuilder Machines
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Machines.MachinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The volumes property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Volumes.VolumesRequestBuilder Volumes
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.Volumes.VolumesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.WithOrgSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrgSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{orgSlug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Orgs.Item.WithOrgSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrgSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{orgSlug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
