// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.V1.Orgs
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\orgs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrgsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Fly.Machines.OpenApiClient.v1.orgs.item collection</summary>
        /// <param name="position">Fly Organization Slug</param>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.Item.WithOrgSlugItemRequestBuilder"/></returns>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.Item.WithOrgSlugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("orgSlug", position);
                return new global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.Item.WithOrgSlugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.OrgsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrgsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/orgs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.OrgsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrgsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/orgs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
