// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.V1.Apps;
using Soenneker.Fly.Machines.OpenApiClient.V1.Orgs;
using Soenneker.Fly.Machines.OpenApiClient.V1.Platform;
using Soenneker.Fly.Machines.OpenApiClient.V1.Postgres;
using Soenneker.Fly.Machines.OpenApiClient.V1.Tokens;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apps property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Apps.AppsRequestBuilder Apps
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Apps.AppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The platform property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Platform.PlatformRequestBuilder Platform
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Platform.PlatformRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The postgres property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.PostgresRequestBuilder Postgres
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.PostgresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokens property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Tokens.TokensRequestBuilder Tokens
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Tokens.TokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
