// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Certificates;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Deploy_token;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Ip_assignments;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Machines;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secrets;
using Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Volumes;
using Soenneker.Fly.Machines.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Apps.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \apps\{app_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithApp_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The certificates property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Certificates.CertificatesRequestBuilder Certificates
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Certificates.CertificatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deploy_token property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Deploy_token.Deploy_tokenRequestBuilder Deploy_token
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Deploy_token.Deploy_tokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ip_assignments property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Ip_assignments.Ip_assignmentsRequestBuilder Ip_assignments
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Ip_assignments.Ip_assignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The machines property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Machines.MachinesRequestBuilder Machines
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Machines.MachinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secretkeys property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.SecretkeysRequestBuilder Secretkeys
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secretkeys.SecretkeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secrets property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secrets.SecretsRequestBuilder Secrets
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Secrets.SecretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The volumes property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Volumes.VolumesRequestBuilder Volumes
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Volumes.VolumesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.WithApp_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithApp_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{app_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.WithApp_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithApp_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/apps/{app_name}", rawUrl)
        {
        }
        /// <summary>
        /// Delete an app by its name.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve details about a specific app by its name.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.App"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fly.Machines.OpenApiClient.Models.App?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fly.Machines.OpenApiClient.Models.App> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fly.Machines.OpenApiClient.Models.App>(requestInfo, global::Soenneker.Fly.Machines.OpenApiClient.Models.App.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete an app by its name.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieve details about a specific app by its name.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.WithApp_nameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.WithApp_nameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Fly.Machines.OpenApiClient.Apps.Item.WithApp_nameItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
