// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.Rl.Checkpoints;
using Soenneker.Fly.Machines.OpenApiClient.Rl.TrainingSessions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Rl
{
    /// <summary>
    /// Builds and executes requests for operations under \rl
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkpoints property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Rl.Checkpoints.CheckpointsRequestBuilder Checkpoints
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Rl.Checkpoints.CheckpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trainingSessions property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Rl.TrainingSessions.TrainingSessionsRequestBuilder TrainingSessions
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.Rl.TrainingSessions.TrainingSessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Rl.RlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Rl.RlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rl", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
