// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Apps.Item.Machines.Item.Wait
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStateQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "started")]
        #pragma warning disable CS1591
        Started,
        #pragma warning restore CS1591
        [EnumMember(Value = "stopped")]
        #pragma warning disable CS1591
        Stopped,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "destroyed")]
        #pragma warning disable CS1591
        Destroyed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "settled")]
        #pragma warning disable CS1591
        Settled,
        #pragma warning restore CS1591
    }
}
