// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CertificateSummary : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acme_alpn_configured property</summary>
        public bool? AcmeAlpnConfigured { get; set; }
        /// <summary>The acme_dns_configured property</summary>
        public bool? AcmeDnsConfigured { get; set; }
        /// <summary>The acme_http_configured property</summary>
        public bool? AcmeHttpConfigured { get; set; }
        /// <summary>The acme_requested property</summary>
        public bool? AcmeRequested { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The configured property</summary>
        public bool? Configured { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The dns_provider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DnsProvider { get; set; }
#nullable restore
#else
        public string DnsProvider { get; set; }
#endif
        /// <summary>The has_custom_certificate property</summary>
        public bool? HasCustomCertificate { get; set; }
        /// <summary>The has_fly_certificate property</summary>
        public bool? HasFlyCertificate { get; set; }
        /// <summary>The hostname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostname { get; set; }
#nullable restore
#else
        public string Hostname { get; set; }
#endif
        /// <summary>The ownership_txt_configured property</summary>
        public bool? OwnershipTxtConfigured { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateSummary"/> and sets the default values.
        /// </summary>
        public CertificateSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acme_alpn_configured", n => { AcmeAlpnConfigured = n.GetBoolValue(); } },
                { "acme_dns_configured", n => { AcmeDnsConfigured = n.GetBoolValue(); } },
                { "acme_http_configured", n => { AcmeHttpConfigured = n.GetBoolValue(); } },
                { "acme_requested", n => { AcmeRequested = n.GetBoolValue(); } },
                { "configured", n => { Configured = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "dns_provider", n => { DnsProvider = n.GetStringValue(); } },
                { "has_custom_certificate", n => { HasCustomCertificate = n.GetBoolValue(); } },
                { "has_fly_certificate", n => { HasFlyCertificate = n.GetBoolValue(); } },
                { "hostname", n => { Hostname = n.GetStringValue(); } },
                { "ownership_txt_configured", n => { OwnershipTxtConfigured = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("acme_alpn_configured", AcmeAlpnConfigured);
            writer.WriteBoolValue("acme_dns_configured", AcmeDnsConfigured);
            writer.WriteBoolValue("acme_http_configured", AcmeHttpConfigured);
            writer.WriteBoolValue("acme_requested", AcmeRequested);
            writer.WriteBoolValue("configured", Configured);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("dns_provider", DnsProvider);
            writer.WriteBoolValue("has_custom_certificate", HasCustomCertificate);
            writer.WriteBoolValue("has_fly_certificate", HasFlyCertificate);
            writer.WriteStringValue("hostname", Hostname);
            writer.WriteBoolValue("ownership_txt_configured", OwnershipTxtConfigured);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
