// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CertificateEntry_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_ownership")]
        #pragma warning disable CS1591
        Pending_ownership,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_validation")]
        #pragma warning disable CS1591
        Pending_validation,
        #pragma warning restore CS1591
    }
}
