// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CertificateCheckResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acme_requested property</summary>
        public bool? AcmeRequested { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The certificates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateEntry>? Certificates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateEntry> Certificates { get; set; }
#endif
        /// <summary>The configured property</summary>
        public bool? Configured { get; set; }
        /// <summary>The dns_provider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DnsProvider { get; set; }
#nullable restore
#else
        public string DnsProvider { get; set; }
#endif
        /// <summary>The dns_records property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords? DnsRecords { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords DnsRecords { get; set; }
#endif
        /// <summary>The dns_requirements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRequirements? DnsRequirements { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRequirements DnsRequirements { get; set; }
#endif
        /// <summary>The hostname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostname { get; set; }
#nullable restore
#else
        public string Hostname { get; set; }
#endif
        /// <summary>The rate_limited_until property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RateLimitedUntil { get; set; }
#nullable restore
#else
        public string RateLimitedUntil { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The validation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidation? Validation { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidation Validation { get; set; }
#endif
        /// <summary>The validation_errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidationError>? ValidationErrors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidationError> ValidationErrors { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateCheckResponse"/> and sets the default values.
        /// </summary>
        public CertificateCheckResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateCheckResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateCheckResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateCheckResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acme_requested", n => { AcmeRequested = n.GetBoolValue(); } },
                { "certificates", n => { Certificates = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateEntry>(global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "configured", n => { Configured = n.GetBoolValue(); } },
                { "dns_provider", n => { DnsProvider = n.GetStringValue(); } },
                { "dns_records", n => { DnsRecords = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords>(global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords.CreateFromDiscriminatorValue); } },
                { "dns_requirements", n => { DnsRequirements = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRequirements>(global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRequirements.CreateFromDiscriminatorValue); } },
                { "hostname", n => { Hostname = n.GetStringValue(); } },
                { "rate_limited_until", n => { RateLimitedUntil = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "validation", n => { Validation = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidation>(global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidation.CreateFromDiscriminatorValue); } },
                { "validation_errors", n => { ValidationErrors = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidationError>(global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidationError.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("acme_requested", AcmeRequested);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateEntry>("certificates", Certificates);
            writer.WriteBoolValue("configured", Configured);
            writer.WriteStringValue("dns_provider", DnsProvider);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords>("dns_records", DnsRecords);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRequirements>("dns_requirements", DnsRequirements);
            writer.WriteStringValue("hostname", Hostname);
            writer.WriteStringValue("rate_limited_until", RateLimitedUntil);
            writer.WriteStringValue("status", Status);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidation>("validation", Validation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.CertificateValidationError>("validation_errors", ValidationErrors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
