// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>Connection pooler mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePostgresClusterRequestPoolMode
    {
        [EnumMember(Value = "session")]
        #pragma warning disable CS1591
        Session,
        #pragma warning restore CS1591
        [EnumMember(Value = "transaction")]
        #pragma warning disable CS1591
        Transaction,
        #pragma warning restore CS1591
    }
}
