// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePostgresClusterRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Disk size in gigabytes.</summary>
        public int? DiskSizeGb { get; set; }
        /// <summary>Name for the cluster. A name is generated when omitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Slug of the organization that will own the cluster.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgSlug { get; set; }
#nullable restore
#else
        public string OrgSlug { get; set; }
#endif
        /// <summary>Postgres major version.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPgMajorVersion? PgMajorVersion { get; set; }
        /// <summary>Plan slug selecting CPU, memory, and disk sizing.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPlan? Plan { get; set; }
        /// <summary>Connection pooler mode.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPoolMode? PoolMode { get; set; }
        /// <summary>Enable PostGIS support, required to later enable PostGIS extensions.</summary>
        public bool? PostgisEnabled { get; set; }
        /// <summary>Fly region code where the cluster&apos;s primary runs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequest"/> and sets the default values.
        /// </summary>
        public CreatePostgresClusterRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disk_size_gb", n => { DiskSizeGb = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "org_slug", n => { OrgSlug = n.GetStringValue(); } },
                { "pg_major_version", n => { PgMajorVersion = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPgMajorVersion>(); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPlan>(); } },
                { "pool_mode", n => { PoolMode = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPoolMode>(); } },
                { "postgis_enabled", n => { PostgisEnabled = n.GetBoolValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("disk_size_gb", DiskSizeGb);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("org_slug", OrgSlug);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPgMajorVersion>("pg_major_version", PgMajorVersion);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPlan>("plan", Plan);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.CreatePostgresClusterRequestPoolMode>("pool_mode", PoolMode);
            writer.WriteBoolValue("postgis_enabled", PostgisEnabled);
            writer.WriteStringValue("region", Region);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
