// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>Postgres major version.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePostgresClusterRequestPgMajorVersion
    {
        [EnumMember(Value = "16")]
        #pragma warning disable CS1591
        Value16,
        #pragma warning restore CS1591
        [EnumMember(Value = "17")]
        #pragma warning disable CS1591
        Value17,
        #pragma warning restore CS1591
    }
}
