// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>Plan slug selecting CPU, memory, and disk sizing.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePostgresClusterRequestPlan
    {
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "starter")]
        #pragma warning disable CS1591
        Starter,
        #pragma warning restore CS1591
        [EnumMember(Value = "launch")]
        #pragma warning disable CS1591
        Launch,
        #pragma warning restore CS1591
        [EnumMember(Value = "scale")]
        #pragma warning disable CS1591
        Scale,
        #pragma warning restore CS1591
        [EnumMember(Value = "Performance")]
        #pragma warning disable CS1591
        Performance,
        #pragma warning restore CS1591
    }
}
