// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DNSRecords : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The a property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? A { get; set; }
#nullable restore
#else
        public List<string> A { get; set; }
#endif
        /// <summary>The aaaa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Aaaa { get; set; }
#nullable restore
#else
        public List<string> Aaaa { get; set; }
#endif
        /// <summary>The acme_challenge_cname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcmeChallengeCname { get; set; }
#nullable restore
#else
        public string AcmeChallengeCname { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cname { get; set; }
#nullable restore
#else
        public List<string> Cname { get; set; }
#endif
        /// <summary>The ownership_txt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnershipTxt { get; set; }
#nullable restore
#else
        public string OwnershipTxt { get; set; }
#endif
        /// <summary>The resolved_addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResolvedAddresses { get; set; }
#nullable restore
#else
        public List<string> ResolvedAddresses { get; set; }
#endif
        /// <summary>The soa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Soa { get; set; }
#nullable restore
#else
        public string Soa { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords"/> and sets the default values.
        /// </summary>
        public DNSRecords()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.DNSRecords();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "a", n => { A = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "aaaa", n => { Aaaa = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "acme_challenge_cname", n => { AcmeChallengeCname = n.GetStringValue(); } },
                { "cname", n => { Cname = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ownership_txt", n => { OwnershipTxt = n.GetStringValue(); } },
                { "resolved_addresses", n => { ResolvedAddresses = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "soa", n => { Soa = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("a", A);
            writer.WriteCollectionOfPrimitiveValues<string>("aaaa", Aaaa);
            writer.WriteStringValue("acme_challenge_cname", AcmeChallengeCname);
            writer.WriteCollectionOfPrimitiveValues<string>("cname", Cname);
            writer.WriteStringValue("ownership_txt", OwnershipTxt);
            writer.WriteCollectionOfPrimitiveValues<string>("resolved_addresses", ResolvedAddresses);
            writer.WriteStringValue("soa", Soa);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
