// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FlyContainerDependencyCondition
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "exited_successfully")]
        #pragma warning disable CS1591
        Exited_successfully,
        #pragma warning restore CS1591
        [EnumMember(Value = "healthy")]
        #pragma warning disable CS1591
        Healthy,
        #pragma warning restore CS1591
        [EnumMember(Value = "started")]
        #pragma warning disable CS1591
        Started,
        #pragma warning restore CS1591
    }
}
