// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyContainerHealthcheck : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The exec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyExecHealthcheck? Exec { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyExecHealthcheck Exec { get; set; }
#endif
        /// <summary>The number of times the check must fail before considering the container unhealthy.</summary>
        public int? FailureThreshold { get; set; }
        /// <summary>The time in seconds to wait after a container starts before checking its health.</summary>
        public int? GracePeriod { get; set; }
        /// <summary>The http property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPHealthcheck? Http { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPHealthcheck Http { get; set; }
#endif
        /// <summary>The time in seconds between executing the defined check.</summary>
        public int? Interval { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheckKind? Kind { get; set; }
        /// <summary>The name of the check. Must be unique within the container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number of times the check must succeeed before considering the container healthy.</summary>
        public int? SuccessThreshold { get; set; }
        /// <summary>The tcp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTCPHealthcheck? Tcp { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTCPHealthcheck Tcp { get; set; }
#endif
        /// <summary>The time in seconds to wait for the check to complete.</summary>
        public int? Timeout { get; set; }
        /// <summary>The unhealthy property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyUnhealthyPolicy? Unhealthy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck"/> and sets the default values.
        /// </summary>
        public FlyContainerHealthcheck()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "exec", n => { Exec = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyExecHealthcheck>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyExecHealthcheck.CreateFromDiscriminatorValue); } },
                { "failure_threshold", n => { FailureThreshold = n.GetIntValue(); } },
                { "grace_period", n => { GracePeriod = n.GetIntValue(); } },
                { "http", n => { Http = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPHealthcheck>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPHealthcheck.CreateFromDiscriminatorValue); } },
                { "interval", n => { Interval = n.GetIntValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheckKind>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "success_threshold", n => { SuccessThreshold = n.GetIntValue(); } },
                { "tcp", n => { Tcp = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTCPHealthcheck>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTCPHealthcheck.CreateFromDiscriminatorValue); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "unhealthy", n => { Unhealthy = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyUnhealthyPolicy>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyExecHealthcheck>("exec", Exec);
            writer.WriteIntValue("failure_threshold", FailureThreshold);
            writer.WriteIntValue("grace_period", GracePeriod);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPHealthcheck>("http", Http);
            writer.WriteIntValue("interval", Interval);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheckKind>("kind", Kind);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("success_threshold", SuccessThreshold);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTCPHealthcheck>("tcp", Tcp);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyUnhealthyPolicy>("unhealthy", Unhealthy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
