// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyContainerConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>CmdOverride is used to override the default command of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cmd { get; set; }
#nullable restore
#else
        public List<string> Cmd { get; set; }
#endif
        /// <summary>DependsOn can be used to define dependencies between containers. The container will only bestarted after all of its dependent conditions have been satisfied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerDependency>? DependsOn { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerDependency> DependsOn { get; set; }
#endif
        /// <summary>EntrypointOverride is used to override the default entrypoint of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Entrypoint { get; set; }
#nullable restore
#else
        public List<string> Entrypoint { get; set; }
#endif
        /// <summary>ExtraEnv is used to add additional environment variables to the container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_env? Env { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_env Env { get; set; }
#endif
        /// <summary>EnvFrom can be provided to set environment variables from machine fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom>? EnvFrom { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom> EnvFrom { get; set; }
#endif
        /// <summary>Image Config overrides - these fields are used to override the image configuration.If not provided, the image configuration will be used.ExecOverride is used to override the default command of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Exec { get; set; }
#nullable restore
#else
        public List<string> Exec { get; set; }
#endif
        /// <summary>Files are files that will be written to the container file system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile> Files { get; set; }
#endif
        /// <summary>Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck>? Healthchecks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck> Healthchecks { get; set; }
#endif
        /// <summary>Image is the docker image to run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>Name is used to identify the container in the machine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>&quot;Restart is used to define the restart policy for the container. NOTE: spot-price is notsupported for containers.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_restart? Restart { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_restart Restart { get; set; }
#endif
        /// <summary>Secrets can be provided at the process level to explicitly indicate which secrets should beused for the process. If not provided, the secrets provided at the machine level will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSecret>? Secrets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSecret> Secrets { get; set; }
#endif
        /// <summary>Stop is used to define the signal and timeout for stopping the container.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_stop? Stop { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_stop Stop { get; set; }
#endif
        /// <summary>UserOverride is used to override the default user of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig"/> and sets the default values.
        /// </summary>
        public FlyContainerConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cmd", n => { Cmd = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "depends_on", n => { DependsOn = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerDependency>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerDependency.CreateFromDiscriminatorValue)?.AsList(); } },
                { "entrypoint", n => { Entrypoint = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "env", n => { Env = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_env>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_env.CreateFromDiscriminatorValue); } },
                { "env_from", n => { EnvFrom = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom.CreateFromDiscriminatorValue)?.AsList(); } },
                { "exec", n => { Exec = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "healthchecks", n => { Healthchecks = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck.CreateFromDiscriminatorValue)?.AsList(); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "restart", n => { Restart = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_restart>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_restart.CreateFromDiscriminatorValue); } },
                { "secrets", n => { Secrets = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSecret>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSecret.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stop", n => { Stop = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_stop>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_stop.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("cmd", Cmd);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerDependency>("depends_on", DependsOn);
            writer.WriteCollectionOfPrimitiveValues<string>("entrypoint", Entrypoint);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_env>("env", Env);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom>("env_from", EnvFrom);
            writer.WriteCollectionOfPrimitiveValues<string>("exec", Exec);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>("files", Files);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerHealthcheck>("healthchecks", Healthchecks);
            writer.WriteStringValue("image", Image);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_restart>("restart", Restart);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSecret>("secrets", Secrets);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig_stop>("stop", Stop);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
