// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>
    /// EnvVar defines an environment variable to be populated from a machine field, env_var
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FlyEnvFrom : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>EnvVar is required and is the name of the environment variable that will be set from thesecret. It must be a valid environment variable name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnvVar { get; set; }
#nullable restore
#else
        public string EnvVar { get; set; }
#endif
        /// <summary>&quot;FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image.&quot;</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom_field_ref? FieldRef { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom"/> and sets the default values.
        /// </summary>
        public FlyEnvFrom()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "env_var", n => { EnvVar = n.GetStringValue(); } },
                { "field_ref", n => { FieldRef = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom_field_ref>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("env_var", EnvVar);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyEnvFrom_field_ref>("field_ref", FieldRef);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
