// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>&quot;FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FlyEnvFromFieldRef
    {
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "version")]
        #pragma warning disable CS1591
        Version,
        #pragma warning restore CS1591
        [EnumMember(Value = "app_name")]
        #pragma warning disable CS1591
        AppName,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_ip")]
        #pragma warning disable CS1591
        PrivateIp,
        #pragma warning restore CS1591
        [EnumMember(Value = "region")]
        #pragma warning disable CS1591
        Region,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
    }
}
