// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>
    /// A file that will be written to the Machine. One of RawValue or SecretName must be set.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FlyFile : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;GuestPath is the path on the machine where the file will be written and must be an absolute path.For example: /full/path/to/file.json&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuestPath { get; set; }
#nullable restore
#else
        public string GuestPath { get; set; }
#endif
        /// <summary>The name of an image to use the OCI image config as the file contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageConfig { get; set; }
#nullable restore
#else
        public string ImageConfig { get; set; }
#endif
        /// <summary>Mode bits used to set permissions on this file as accepted by chmod(2).</summary>
        public int? Mode { get; set; }
        /// <summary>The base64 encoded string of the file contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawValue { get; set; }
#nullable restore
#else
        public string RawValue { get; set; }
#endif
        /// <summary>The name of the secret that contains the base64 encoded file contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecretName { get; set; }
#nullable restore
#else
        public string SecretName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile"/> and sets the default values.
        /// </summary>
        public FlyFile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "guest_path", n => { GuestPath = n.GetStringValue(); } },
                { "image_config", n => { ImageConfig = n.GetStringValue(); } },
                { "mode", n => { Mode = n.GetIntValue(); } },
                { "raw_value", n => { RawValue = n.GetStringValue(); } },
                { "secret_name", n => { SecretName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("guest_path", GuestPath);
            writer.WriteStringValue("image_config", ImageConfig);
            writer.WriteIntValue("mode", Mode);
            writer.WriteStringValue("raw_value", RawValue);
            writer.WriteStringValue("secret_name", SecretName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
