// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyHttpOptions : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The compress property</summary>
        public bool? Compress { get; set; }
        /// <summary>The h2_backend property</summary>
        public bool? H2Backend { get; set; }
        /// <summary>The headers_read_timeout property</summary>
        public int? HeadersReadTimeout { get; set; }
        /// <summary>The idle_timeout property</summary>
        public int? IdleTimeout { get; set; }
        /// <summary>The replay_cache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache>? ReplayCache { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache> ReplayCache { get; set; }
#endif
        /// <summary>The response property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpResponseOptions? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpResponseOptions Response { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpOptions"/> and sets the default values.
        /// </summary>
        public FlyHttpOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compress", n => { Compress = n.GetBoolValue(); } },
                { "h2_backend", n => { H2Backend = n.GetBoolValue(); } },
                { "headers_read_timeout", n => { HeadersReadTimeout = n.GetIntValue(); } },
                { "idle_timeout", n => { IdleTimeout = n.GetIntValue(); } },
                { "replay_cache", n => { ReplayCache = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache.CreateFromDiscriminatorValue)?.AsList(); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpResponseOptions>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpResponseOptions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("compress", Compress);
            writer.WriteBoolValue("h2_backend", H2Backend);
            writer.WriteIntValue("headers_read_timeout", HeadersReadTimeout);
            writer.WriteIntValue("idle_timeout", IdleTimeout);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache>("replay_cache", ReplayCache);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpResponseOptions>("response", Response);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
