// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyHttpHealthcheck : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional headers to send with the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHttpHeader>? Headers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHttpHeader> Headers { get; set; }
#endif
        /// <summary>The HTTP method to use to when making the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Method { get; set; }
#nullable restore
#else
        public string Method { get; set; }
#endif
        /// <summary>The path to send the request to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The port to connect to, often the same as internal_port</summary>
        public int? Port { get; set; }
        /// <summary>Whether to use http or https</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheckScheme? Scheme { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheckScheme Scheme { get; set; }
#endif
        /// <summary>If the protocol is https, the hostname to use for TLS certificate validation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsServerName { get; set; }
#nullable restore
#else
        public string TlsServerName { get; set; }
#endif
        /// <summary>If the protocol is https, whether or not to verify the TLS certificate</summary>
        public bool? TlsSkipVerify { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheck"/> and sets the default values.
        /// </summary>
        public FlyHttpHealthcheck()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheck"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheck CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheck();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "headers", n => { Headers = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHttpHeader>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHttpHeader.CreateFromDiscriminatorValue)?.AsList(); } },
                { "method", n => { Method = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "scheme", n => { Scheme = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheckScheme>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheckScheme.CreateFromDiscriminatorValue); } },
                { "tls_server_name", n => { TlsServerName = n.GetStringValue(); } },
                { "tls_skip_verify", n => { TlsSkipVerify = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHttpHeader>("headers", Headers);
            writer.WriteStringValue("method", Method);
            writer.WriteStringValue("path", Path);
            writer.WriteIntValue("port", Port);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHttpHealthcheckScheme>("scheme", Scheme);
            writer.WriteStringValue("tls_server_name", TlsServerName);
            writer.WriteBoolValue("tls_skip_verify", TlsSkipVerify);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
