// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.* always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.* on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FlyMachineRestartPolicy
    {
        [EnumMember(Value = "no")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "always")]
        #pragma warning disable CS1591
        Always,
        #pragma warning restore CS1591
        [EnumMember(Value = "on-failure")]
        #pragma warning disable CS1591
        OnFailure,
        #pragma warning restore CS1591
    }
}
