// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachineGuest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cpu_kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CpuKind { get; set; }
#nullable restore
#else
        public string CpuKind { get; set; }
#endif
        /// <summary>The cpus property</summary>
        public int? Cpus { get; set; }
        /// <summary>The gpu_kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GpuKind { get; set; }
#nullable restore
#else
        public string GpuKind { get; set; }
#endif
        /// <summary>The gpus property</summary>
        public int? Gpus { get; set; }
        /// <summary>The host_dedication_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostDedicationId { get; set; }
#nullable restore
#else
        public string HostDedicationId { get; set; }
#endif
        /// <summary>The kernel_args property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? KernelArgs { get; set; }
#nullable restore
#else
        public List<string> KernelArgs { get; set; }
#endif
        /// <summary>The max_memory_mb property</summary>
        public int? MaxMemoryMb { get; set; }
        /// <summary>The memory_mb property</summary>
        public int? MemoryMb { get; set; }
        /// <summary>&quot;Deprecated: use MachineConfig.Rootfs instead&quot;</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest_persist_rootfs? PersistRootfs { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest"/> and sets the default values.
        /// </summary>
        public FlyMachineGuest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpu_kind", n => { CpuKind = n.GetStringValue(); } },
                { "cpus", n => { Cpus = n.GetIntValue(); } },
                { "gpu_kind", n => { GpuKind = n.GetStringValue(); } },
                { "gpus", n => { Gpus = n.GetIntValue(); } },
                { "host_dedication_id", n => { HostDedicationId = n.GetStringValue(); } },
                { "kernel_args", n => { KernelArgs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "max_memory_mb", n => { MaxMemoryMb = n.GetIntValue(); } },
                { "memory_mb", n => { MemoryMb = n.GetIntValue(); } },
                { "persist_rootfs", n => { PersistRootfs = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest_persist_rootfs>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cpu_kind", CpuKind);
            writer.WriteIntValue("cpus", Cpus);
            writer.WriteStringValue("gpu_kind", GpuKind);
            writer.WriteIntValue("gpus", Gpus);
            writer.WriteStringValue("host_dedication_id", HostDedicationId);
            writer.WriteCollectionOfPrimitiveValues<string>("kernel_args", KernelArgs);
            writer.WriteIntValue("max_memory_mb", MaxMemoryMb);
            writer.WriteIntValue("memory_mb", MemoryMb);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest_persist_rootfs>("persist_rootfs", PersistRootfs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
