// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachineInit : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cmd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cmd { get; set; }
#nullable restore
#else
        public List<string> Cmd { get; set; }
#endif
        /// <summary>The entrypoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Entrypoint { get; set; }
#nullable restore
#else
        public List<string> Entrypoint { get; set; }
#endif
        /// <summary>The exec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Exec { get; set; }
#nullable restore
#else
        public List<string> Exec { get; set; }
#endif
        /// <summary>The kernel_args property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? KernelArgs { get; set; }
#nullable restore
#else
        public List<string> KernelArgs { get; set; }
#endif
        /// <summary>The swap_size_mb property</summary>
        public int? SwapSizeMb { get; set; }
        /// <summary>The tty property</summary>
        public bool? Tty { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit"/> and sets the default values.
        /// </summary>
        public FlyMachineInit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cmd", n => { Cmd = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "entrypoint", n => { Entrypoint = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "exec", n => { Exec = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "kernel_args", n => { KernelArgs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "swap_size_mb", n => { SwapSizeMb = n.GetIntValue(); } },
                { "tty", n => { Tty = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("cmd", Cmd);
            writer.WriteCollectionOfPrimitiveValues<string>("entrypoint", Entrypoint);
            writer.WriteCollectionOfPrimitiveValues<string>("exec", Exec);
            writer.WriteCollectionOfPrimitiveValues<string>("kernel_args", KernelArgs);
            writer.WriteIntValue("swap_size_mb", SwapSizeMb);
            writer.WriteBoolValue("tty", Tty);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
