// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachinePort : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The end_port property</summary>
        public int? EndPort { get; set; }
        /// <summary>The force_https property</summary>
        public bool? ForceHttps { get; set; }
        /// <summary>The handlers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Handlers { get; set; }
#nullable restore
#else
        public List<string> Handlers { get; set; }
#endif
        /// <summary>The http_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPOptions? HttpOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPOptions HttpOptions { get; set; }
#endif
        /// <summary>The port property</summary>
        public int? Port { get; set; }
        /// <summary>The proxy_proto_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyProxyProtoOptions? ProxyProtoOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyProxyProtoOptions ProxyProtoOptions { get; set; }
#endif
        /// <summary>The start_port property</summary>
        public int? StartPort { get; set; }
        /// <summary>The tls_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTLSOptions? TlsOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTLSOptions TlsOptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort"/> and sets the default values.
        /// </summary>
        public FlyMachinePort()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_port", n => { EndPort = n.GetIntValue(); } },
                { "force_https", n => { ForceHttps = n.GetBoolValue(); } },
                { "handlers", n => { Handlers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "http_options", n => { HttpOptions = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPOptions>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPOptions.CreateFromDiscriminatorValue); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "proxy_proto_options", n => { ProxyProtoOptions = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyProxyProtoOptions>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyProxyProtoOptions.CreateFromDiscriminatorValue); } },
                { "start_port", n => { StartPort = n.GetIntValue(); } },
                { "tls_options", n => { TlsOptions = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTLSOptions>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTLSOptions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("end_port", EndPort);
            writer.WriteBoolValue("force_https", ForceHttps);
            writer.WriteCollectionOfPrimitiveValues<string>("handlers", Handlers);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyHTTPOptions>("http_options", HttpOptions);
            writer.WriteIntValue("port", Port);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyProxyProtoOptions>("proxy_proto_options", ProxyProtoOptions);
            writer.WriteIntValue("start_port", StartPort);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyTLSOptions>("tls_options", TlsOptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
