// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachineService : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The autostart property</summary>
        public bool? Autostart { get; set; }
        /// <summary>Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for &quot;off&quot; and &quot;stop&quot; in responses.* &quot;off&quot; or false - Do not autostop the Machine.* &quot;stop&quot; or true - Automatically stop the Machine.* &quot;suspend&quot; - Automatically suspend the Machine, falling back to a full stop if this is not possible.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceAutostop? Autostop { get; set; }
        /// <summary>An optional list of service checks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck>? Checks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck> Checks { get; set; }
#endif
        /// <summary>The concurrency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceConcurrency? Concurrency { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceConcurrency Concurrency { get; set; }
#endif
        /// <summary>The force_instance_description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForceInstanceDescription { get; set; }
#nullable restore
#else
        public string ForceInstanceDescription { get; set; }
#endif
        /// <summary>The force_instance_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForceInstanceKey { get; set; }
#nullable restore
#else
        public string ForceInstanceKey { get; set; }
#endif
        /// <summary>The internal_port property</summary>
        public int? InternalPort { get; set; }
        /// <summary>The min_machines_running property</summary>
        public int? MinMachinesRunning { get; set; }
        /// <summary>The ports property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort>? Ports { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort> Ports { get; set; }
#endif
        /// <summary>The protocol property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Protocol { get; set; }
#nullable restore
#else
        public string Protocol { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService"/> and sets the default values.
        /// </summary>
        public FlyMachineService()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autostart", n => { Autostart = n.GetBoolValue(); } },
                { "autostop", n => { Autostop = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceAutostop>(); } },
                { "checks", n => { Checks = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck.CreateFromDiscriminatorValue)?.AsList(); } },
                { "concurrency", n => { Concurrency = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceConcurrency>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceConcurrency.CreateFromDiscriminatorValue); } },
                { "force_instance_description", n => { ForceInstanceDescription = n.GetStringValue(); } },
                { "force_instance_key", n => { ForceInstanceKey = n.GetStringValue(); } },
                { "internal_port", n => { InternalPort = n.GetIntValue(); } },
                { "min_machines_running", n => { MinMachinesRunning = n.GetIntValue(); } },
                { "ports", n => { Ports = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort.CreateFromDiscriminatorValue)?.AsList(); } },
                { "protocol", n => { Protocol = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("autostart", Autostart);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceAutostop>("autostop", Autostop);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck>("checks", Checks);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceConcurrency>("concurrency", Concurrency);
            writer.WriteStringValue("force_instance_description", ForceInstanceDescription);
            writer.WriteStringValue("force_instance_key", ForceInstanceKey);
            writer.WriteIntValue("internal_port", InternalPort);
            writer.WriteIntValue("min_machines_running", MinMachinesRunning);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachinePort>("ports", Ports);
            writer.WriteStringValue("protocol", Protocol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
