// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachineConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional boolean telling the Machine to destroy itself once it’s complete (default false)</summary>
        public bool? AutoDestroy { get; set; }
        /// <summary>The cache_drive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineCacheDrive? CacheDrive { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineCacheDrive CacheDrive { get; set; }
#endif
        /// <summary>An optional object that defines one or more named top-level checks. The key for each check is the check name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigChecksProperty? Checks { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigChecksProperty Checks { get; set; }
#endif
        /// <summary>Containers are a list of containers that will run in the machine. Currently restricted toonly specific organizations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig>? Containers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig> Containers { get; set; }
#endif
        /// <summary>&quot;Deprecated: use Service.Autostart instead&quot;</summary>
        public bool? DisableMachineAutostart { get; set; }
        /// <summary>The dns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyDnsConfig? Dns { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyDnsConfig Dns { get; set; }
#endif
        /// <summary>An object filled with key/value pairs to be set as environment variables</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigEnvProperty? Env { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigEnvProperty Env { get; set; }
#endif
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile> Files { get; set; }
#endif
        /// <summary>The guest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest? Guest { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest Guest { get; set; }
#endif
        /// <summary>The docker image to run</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>The init property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit? Init { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit Init { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigMetadataProperty Metadata { get; set; }
#endif
        /// <summary>The metrics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMetrics? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMetrics Metrics { get; set; }
#endif
        /// <summary>The mounts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMount>? Mounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMount> Mounts { get; set; }
#endif
        /// <summary>The processes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineProcess>? Processes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineProcess> Processes { get; set; }
#endif
        /// <summary>The Machine restart policy defines whether and how flyd restarts a Machine after its main process exits. See https://fly.io/docs/machines/guides-examples/machine-restart-policy/.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRestart? Restart { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRestart Restart { get; set; }
#endif
        /// <summary>The rootfs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRootfs? Rootfs { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRootfs Rootfs { get; set; }
#endif
        /// <summary>The schedule property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Schedule { get; set; }
#nullable restore
#else
        public string Schedule { get; set; }
#endif
        /// <summary>The services property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService>? Services { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService> Services { get; set; }
#endif
        /// <summary>&quot;Deprecated: use Guest instead&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The spot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSpot? Spot { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSpot Spot { get; set; }
#endif
        /// <summary>Standbys enable a machine to be a standby for another. In the event of a hardware failure,the standby machine will be started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Standbys { get; set; }
#nullable restore
#else
        public List<string> Standbys { get; set; }
#endif
        /// <summary>The statics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStatic>? Statics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStatic> Statics { get; set; }
#endif
        /// <summary>The stop_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStopConfig? StopConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStopConfig StopConfig { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfig"/> and sets the default values.
        /// </summary>
        public FlyMachineConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_destroy", n => { AutoDestroy = n.GetBoolValue(); } },
                { "cache_drive", n => { CacheDrive = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineCacheDrive>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineCacheDrive.CreateFromDiscriminatorValue); } },
                { "checks", n => { Checks = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigChecksProperty>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigChecksProperty.CreateFromDiscriminatorValue); } },
                { "containers", n => { Containers = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig.CreateFromDiscriminatorValue)?.AsList(); } },
                { "disable_machine_autostart", n => { DisableMachineAutostart = n.GetBoolValue(); } },
                { "dns", n => { Dns = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyDnsConfig>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyDnsConfig.CreateFromDiscriminatorValue); } },
                { "env", n => { Env = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigEnvProperty>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigEnvProperty.CreateFromDiscriminatorValue); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "guest", n => { Guest = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest.CreateFromDiscriminatorValue); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "init", n => { Init = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigMetadataProperty>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigMetadataProperty.CreateFromDiscriminatorValue); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMetrics>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMetrics.CreateFromDiscriminatorValue); } },
                { "mounts", n => { Mounts = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMount>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "processes", n => { Processes = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineProcess>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineProcess.CreateFromDiscriminatorValue)?.AsList(); } },
                { "restart", n => { Restart = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRestart>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRestart.CreateFromDiscriminatorValue); } },
                { "rootfs", n => { Rootfs = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRootfs>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRootfs.CreateFromDiscriminatorValue); } },
                { "schedule", n => { Schedule = n.GetStringValue(); } },
                { "services", n => { Services = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService.CreateFromDiscriminatorValue)?.AsList(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "spot", n => { Spot = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSpot>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSpot.CreateFromDiscriminatorValue); } },
                { "standbys", n => { Standbys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "statics", n => { Statics = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStatic>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStatic.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stop_config", n => { StopConfig = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStopConfig>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStopConfig.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto_destroy", AutoDestroy);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineCacheDrive>("cache_drive", CacheDrive);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigChecksProperty>("checks", Checks);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyContainerConfig>("containers", Containers);
            writer.WriteBoolValue("disable_machine_autostart", DisableMachineAutostart);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyDnsConfig>("dns", Dns);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigEnvProperty>("env", Env);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyFile>("files", Files);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineGuest>("guest", Guest);
            writer.WriteStringValue("image", Image);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineInit>("init", Init);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineConfigMetadataProperty>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMetrics>("metrics", Metrics);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineMount>("mounts", Mounts);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineProcess>("processes", Processes);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRestart>("restart", Restart);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineRootfs>("rootfs", Rootfs);
            writer.WriteStringValue("schedule", Schedule);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineService>("services", Services);
            writer.WriteStringValue("size", Size);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineSpot>("spot", Spot);
            writer.WriteCollectionOfPrimitiveValues<string>("standbys", Standbys);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStatic>("statics", Statics);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyStopConfig>("stop_config", StopConfig);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
