// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>&quot;Deprecated: use MachineConfig.Rootfs instead&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FlyMachineGuest_persist_rootfs
    {
        [EnumMember(Value = "never")]
        #pragma warning disable CS1591
        Never,
        #pragma warning restore CS1591
        [EnumMember(Value = "always")]
        #pragma warning disable CS1591
        Always,
        #pragma warning restore CS1591
        [EnumMember(Value = "restart")]
        #pragma warning disable CS1591
        Restart,
        #pragma warning restore CS1591
    }
}
