// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyMachineServiceCheck : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time to wait after a VM starts before checking its health</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GracePeriod { get; set; }
#nullable restore
#else
        public string GracePeriod { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHTTPHeader>? Headers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHTTPHeader> Headers { get; set; }
#endif
        /// <summary>The time between connectivity checks</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Interval { get; set; }
#nullable restore
#else
        public string Interval { get; set; }
#endif
        /// <summary>For http checks, the HTTP method to use to when making the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Method { get; set; }
#nullable restore
#else
        public string Method { get; set; }
#endif
        /// <summary>For http checks, the path to send the request to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The port to connect to, often the same as internal_port</summary>
        public int? Port { get; set; }
        /// <summary>For http checks, whether to use http or https</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Protocol { get; set; }
#nullable restore
#else
        public string Protocol { get; set; }
#endif
        /// <summary>The maximum time a connection can take before being reported as failing its health check</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timeout { get; set; }
#nullable restore
#else
        public string Timeout { get; set; }
#endif
        /// <summary>If the protocol is https, the hostname to use for TLS certificate validation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsServerName { get; set; }
#nullable restore
#else
        public string TlsServerName { get; set; }
#endif
        /// <summary>For http checks with https protocol, whether or not to verify the TLS certificate</summary>
        public bool? TlsSkipVerify { get; set; }
        /// <summary>tcp or http</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck"/> and sets the default values.
        /// </summary>
        public FlyMachineServiceCheck()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineServiceCheck();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "grace_period", n => { GracePeriod = n.GetStringValue(); } },
                { "headers", n => { Headers = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHTTPHeader>(global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHTTPHeader.CreateFromDiscriminatorValue)?.AsList(); } },
                { "interval", n => { Interval = n.GetStringValue(); } },
                { "method", n => { Method = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "port", n => { Port = n.GetIntValue(); } },
                { "protocol", n => { Protocol = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetStringValue(); } },
                { "tls_server_name", n => { TlsServerName = n.GetStringValue(); } },
                { "tls_skip_verify", n => { TlsSkipVerify = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("grace_period", GracePeriod);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyMachineHTTPHeader>("headers", Headers);
            writer.WriteStringValue("interval", Interval);
            writer.WriteStringValue("method", Method);
            writer.WriteStringValue("path", Path);
            writer.WriteIntValue("port", Port);
            writer.WriteStringValue("protocol", Protocol);
            writer.WriteStringValue("timeout", Timeout);
            writer.WriteStringValue("tls_server_name", TlsServerName);
            writer.WriteBoolValue("tls_skip_verify", TlsSkipVerify);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
