// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlyReplayCache : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allow_bypass property</summary>
        public bool? AllowBypass { get; set; }
        /// <summary>Name of the cookie or header to key the cache on</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The path_prefix property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PathPrefix { get; set; }
#nullable restore
#else
        public string PathPrefix { get; set; }
#endif
        /// <summary>The ttl_seconds property</summary>
        public int? TtlSeconds { get; set; }
        /// <summary>Currently either &quot;cookie&quot; or &quot;header&quot;</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache"/> and sets the default values.
        /// </summary>
        public FlyReplayCache()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_bypass", n => { AllowBypass = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "path_prefix", n => { PathPrefix = n.GetStringValue(); } },
                { "ttl_seconds", n => { TtlSeconds = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_bypass", AllowBypass);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("path_prefix", PathPrefix);
            writer.WriteIntValue("ttl_seconds", TtlSeconds);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.FlyReplayCache_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
