// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>Type of IP address to allocate. &quot;egress-pair&quot; allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum IpAssignmentType
    {
        [EnumMember(Value = "v4")]
        #pragma warning disable CS1591
        V4,
        #pragma warning restore CS1591
        [EnumMember(Value = "v6")]
        #pragma warning disable CS1591
        V6,
        #pragma warning restore CS1591
        [EnumMember(Value = "shared_v4")]
        #pragma warning disable CS1591
        SharedV4,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_v6")]
        #pragma warning disable CS1591
        PrivateV6,
        #pragma warning restore CS1591
        [EnumMember(Value = "egress_v4")]
        #pragma warning disable CS1591
        EgressV4,
        #pragma warning restore CS1591
        [EnumMember(Value = "egress_v6")]
        #pragma warning disable CS1591
        EgressV6,
        #pragma warning restore CS1591
        [EnumMember(Value = "egress_pair")]
        #pragma warning disable CS1591
        EgressPair,
        #pragma warning restore CS1591
    }
}
