// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MainStatusCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "insufficient_capacity")]
        #pragma warning disable CS1591
        InsufficientCapacity,
        #pragma warning restore CS1591
        [EnumMember(Value = "volume_placement_capacity")]
        #pragma warning disable CS1591
        VolumePlacementCapacity,
        #pragma warning restore CS1591
        [EnumMember(Value = "name_taken")]
        #pragma warning disable CS1591
        NameTaken,
        #pragma warning restore CS1591
    }
}
