// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MainTokenAccess : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>&quot;Action is the action being taken on the specified resource. This is thecombination of individual action characters (e.g \&quot;rw\&quot;)  - r: read  - w: write  - c: create  - d: delete  - C: control&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccessAction? Action { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccessAction Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;AppFeature is a named set of functionality associated with the app. Ifthis is specified, the AppName field must be set.  - images: images in the fly.io registry&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppFeature { get; set; }
#nullable restore
#else
        public string AppFeature { get; set; }
#endif
        /// <summary>AppName is the name of the app being accessed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppName { get; set; }
#nullable restore
#else
        public string AppName { get; set; }
#endif
        /// <summary>Command is the command being executed on a machine. If this is specified,the Machine must be set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Command { get; set; }
#nullable restore
#else
        public List<string> Command { get; set; }
#endif
        /// <summary>&quot;MachineFeature is a named set of functionality associated with themachine. If this is specified, the Machine field must be set.  - metadata: machine metadata service  - oidc: OIDC tokens  - kmstoken: Petsem tokens for KMS access&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineFeature { get; set; }
#nullable restore
#else
        public string MachineFeature { get; set; }
#endif
        /// <summary>MachineID is the ID of the machine being accessed (e.g. 7811701f564258).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MachineId { get; set; }
#nullable restore
#else
        public string MachineId { get; set; }
#endif
        /// <summary>Mutation is the GraphQL mutation being performed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mutation { get; set; }
#nullable restore
#else
        public string Mutation { get; set; }
#endif
        /// <summary>&quot;OrgFeature is a named set of functionality associated with theorganization. If this is specified, the OrgSlug field must be set.  - wg: WireGuard peers  - builder: remote builders  - addon: addons  - membership: organization membership  - billing: billing  - litefs-cloud: LiteFS Cloud  - authentication: authentication settings&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgFeature { get; set; }
#nullable restore
#else
        public string OrgFeature { get; set; }
#endif
        /// <summary>OrgSlug is the slug of the organization being accessed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgSlug { get; set; }
#nullable restore
#else
        public string OrgSlug { get; set; }
#endif
        /// <summary>SourceMachine is the machine ID of the actor attempting access.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceMachine { get; set; }
#nullable restore
#else
        public string SourceMachine { get; set; }
#endif
        /// <summary>StorageObject is the storage object being accessed. If this is specified,the OrgSlug must be set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageObject { get; set; }
#nullable restore
#else
        public string StorageObject { get; set; }
#endif
        /// <summary>VolumeID is the encoded ID of the volume being accessed (e.g.vol_r1p6pln1k9m9j7zr).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VolumeId { get; set; }
#nullable restore
#else
        public string VolumeId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccess"/> and sets the default values.
        /// </summary>
        public MainTokenAccess()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccess"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccess CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccess();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccessAction>(global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccessAction.CreateFromDiscriminatorValue); } },
                { "app_feature", n => { AppFeature = n.GetStringValue(); } },
                { "app_name", n => { AppName = n.GetStringValue(); } },
                { "command", n => { Command = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "machine_feature", n => { MachineFeature = n.GetStringValue(); } },
                { "machine_id", n => { MachineId = n.GetStringValue(); } },
                { "mutation", n => { Mutation = n.GetStringValue(); } },
                { "org_feature", n => { OrgFeature = n.GetStringValue(); } },
                { "org_slug", n => { OrgSlug = n.GetStringValue(); } },
                { "source_machine", n => { SourceMachine = n.GetStringValue(); } },
                { "storage_object", n => { StorageObject = n.GetStringValue(); } },
                { "volume_id", n => { VolumeId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainTokenAccessAction>("action", Action);
            writer.WriteStringValue("app_feature", AppFeature);
            writer.WriteStringValue("app_name", AppName);
            writer.WriteCollectionOfPrimitiveValues<string>("command", Command);
            writer.WriteStringValue("machine_feature", MachineFeature);
            writer.WriteStringValue("machine_id", MachineId);
            writer.WriteStringValue("mutation", Mutation);
            writer.WriteStringValue("org_feature", OrgFeature);
            writer.WriteStringValue("org_slug", OrgSlug);
            writer.WriteStringValue("source_machine", SourceMachine);
            writer.WriteStringValue("storage_object", StorageObject);
            writer.WriteStringValue("volume_id", VolumeId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
