// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MainGetPlacementsRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Resource requirements for the Machine to simulate. Defaults to a performance-1x machine</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_compute? Compute { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_compute Compute { get; set; }
#endif
        /// <summary>Number of machines to simulate placement.Defaults to 0, which returns the org-specific limit for each region.</summary>
        public int? Count { get; set; }
        /// <summary>The org_slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgSlug { get; set; }
#nullable restore
#else
        public string OrgSlug { get; set; }
#endif
        /// <summary>Region expression for placement as a comma-delimited set of regions or aliases.Defaults to &quot;[region],any&quot;, to prefer the API endpoint&apos;s local region with any other region as fallback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The volume_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VolumeName { get; set; }
#nullable restore
#else
        public string VolumeName { get; set; }
#endif
        /// <summary>The volume_size_bytes property</summary>
        public int? VolumeSizeBytes { get; set; }
        /// <summary>Optional weights to override default placement preferences.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_weights? Weights { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_weights Weights { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest"/> and sets the default values.
        /// </summary>
        public MainGetPlacementsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compute", n => { Compute = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_compute>(global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_compute.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "org_slug", n => { OrgSlug = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "volume_name", n => { VolumeName = n.GetStringValue(); } },
                { "volume_size_bytes", n => { VolumeSizeBytes = n.GetIntValue(); } },
                { "weights", n => { Weights = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_weights>(global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_weights.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_compute>("compute", Compute);
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("org_slug", OrgSlug);
            writer.WriteStringValue("region", Region);
            writer.WriteStringValue("volume_name", VolumeName);
            writer.WriteIntValue("volume_size_bytes", VolumeSizeBytes);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.MainGetPlacementsRequest_weights>("weights", Weights);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
