// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OrgVolumeType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
        [EnumMember(Value = "cache")]
        #pragma warning disable CS1591
        Cache,
        #pragma warning restore CS1591
    }
}
