// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrgVolume : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The app_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppName { get; set; }
#nullable restore
#else
        public string AppName { get; set; }
#endif
        /// <summary>The attached_alloc_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachedAllocId { get; set; }
#nullable restore
#else
        public string AttachedAllocId { get; set; }
#endif
        /// <summary>The attached_machine_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AttachedMachineId { get; set; }
#nullable restore
#else
        public string AttachedMachineId { get; set; }
#endif
        /// <summary>The auto_backup_enabled property</summary>
        public bool? AutoBackupEnabled { get; set; }
        /// <summary>The blocks property</summary>
        public int? Blocks { get; set; }
        /// <summary>The blocks_avail property</summary>
        public int? BlocksAvail { get; set; }
        /// <summary>The blocks_free property</summary>
        public int? BlocksFree { get; set; }
        /// <summary>The block_size property</summary>
        public int? BlockSize { get; set; }
        /// <summary>The bytes_total property</summary>
        public int? BytesTotal { get; set; }
        /// <summary>The bytes_used property</summary>
        public int? BytesUsed { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The encrypted property</summary>
        public bool? Encrypted { get; set; }
        /// <summary>The fstype property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fstype { get; set; }
#nullable restore
#else
        public string Fstype { get; set; }
#endif
        /// <summary>The host_status property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeHostStatus? HostStatus { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The size_gb property</summary>
        public int? SizeGb { get; set; }
        /// <summary>The snapshot_retention property</summary>
        public int? SnapshotRetention { get; set; }
        /// <summary>The state property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeType? Type { get; set; }
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The zone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zone { get; set; }
#nullable restore
#else
        public string Zone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolume"/> and sets the default values.
        /// </summary>
        public OrgVolume()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolume"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolume CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolume();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_name", n => { AppName = n.GetStringValue(); } },
                { "attached_alloc_id", n => { AttachedAllocId = n.GetStringValue(); } },
                { "attached_machine_id", n => { AttachedMachineId = n.GetStringValue(); } },
                { "auto_backup_enabled", n => { AutoBackupEnabled = n.GetBoolValue(); } },
                { "block_size", n => { BlockSize = n.GetIntValue(); } },
                { "blocks", n => { Blocks = n.GetIntValue(); } },
                { "blocks_avail", n => { BlocksAvail = n.GetIntValue(); } },
                { "blocks_free", n => { BlocksFree = n.GetIntValue(); } },
                { "bytes_total", n => { BytesTotal = n.GetIntValue(); } },
                { "bytes_used", n => { BytesUsed = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "encrypted", n => { Encrypted = n.GetBoolValue(); } },
                { "fstype", n => { Fstype = n.GetStringValue(); } },
                { "host_status", n => { HostStatus = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeHostStatus>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "size_gb", n => { SizeGb = n.GetIntValue(); } },
                { "snapshot_retention", n => { SnapshotRetention = n.GetIntValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "zone", n => { Zone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_name", AppName);
            writer.WriteStringValue("attached_alloc_id", AttachedAllocId);
            writer.WriteStringValue("attached_machine_id", AttachedMachineId);
            writer.WriteBoolValue("auto_backup_enabled", AutoBackupEnabled);
            writer.WriteIntValue("blocks", Blocks);
            writer.WriteIntValue("blocks_avail", BlocksAvail);
            writer.WriteIntValue("blocks_free", BlocksFree);
            writer.WriteIntValue("block_size", BlockSize);
            writer.WriteIntValue("bytes_total", BytesTotal);
            writer.WriteIntValue("bytes_used", BytesUsed);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("encrypted", Encrypted);
            writer.WriteStringValue("fstype", Fstype);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeHostStatus>("host_status", HostStatus);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("region", Region);
            writer.WriteIntValue("size_gb", SizeGb);
            writer.WriteIntValue("snapshot_retention", SnapshotRetention);
            writer.WriteStringValue("state", State);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrgVolumeType>("type", Type);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("zone", Zone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
