// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OrgVolumeHostStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ok")]
        #pragma warning disable CS1591
        Ok,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "unreachable")]
        #pragma warning disable CS1591
        Unreachable,
        #pragma warning restore CS1591
    }
}
