// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostgresSlowQuery : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Cumulative number of executions.</summary>
        public int? Calls { get; set; }
        /// <summary>Database name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Database { get; set; }
#nullable restore
#else
        public string Database { get; set; }
#endif
        /// <summary>Maximum execution time in seconds.</summary>
        public double? MaxExecTimeSeconds { get; set; }
        /// <summary>Mean execution time in seconds.</summary>
        public double? MeanExecTimeSeconds { get; set; }
        /// <summary>Full query pattern.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Query identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueryId { get; set; }
#nullable restore
#else
        public string QueryId { get; set; }
#endif
        /// <summary>Cumulative total execution time in seconds.</summary>
        public double? TotalExecTimeSeconds { get; set; }
        /// <summary>User running the query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresSlowQuery"/> and sets the default values.
        /// </summary>
        public PostgresSlowQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresSlowQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresSlowQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresSlowQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calls", n => { Calls = n.GetIntValue(); } },
                { "database", n => { Database = n.GetStringValue(); } },
                { "max_exec_time_seconds", n => { MaxExecTimeSeconds = n.GetDoubleValue(); } },
                { "mean_exec_time_seconds", n => { MeanExecTimeSeconds = n.GetDoubleValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "query_id", n => { QueryId = n.GetStringValue(); } },
                { "total_exec_time_seconds", n => { TotalExecTimeSeconds = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("calls", Calls);
            writer.WriteStringValue("database", Database);
            writer.WriteDoubleValue("max_exec_time_seconds", MaxExecTimeSeconds);
            writer.WriteDoubleValue("mean_exec_time_seconds", MeanExecTimeSeconds);
            writer.WriteStringValue("query", Query);
            writer.WriteStringValue("query_id", QueryId);
            writer.WriteDoubleValue("total_exec_time_seconds", TotalExecTimeSeconds);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
