// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>Backup type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostgresBackupType
    {
        [EnumMember(Value = "full")]
        #pragma warning disable CS1591
        Full,
        #pragma warning restore CS1591
        [EnumMember(Value = "incr")]
        #pragma warning disable CS1591
        Incr,
        #pragma warning restore CS1591
        [EnumMember(Value = "diff")]
        #pragma warning disable CS1591
        Diff,
        #pragma warning restore CS1591
    }
}
