// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostgresCluster : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Apps attached to the cluster.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresAttachedApp>? AttachedApps { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresAttachedApp> AttachedApps { get; set; }
#endif
        /// <summary>CPU class.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterCpuKind? CpuKind { get; set; }
        /// <summary>vCPUs per node.</summary>
        public int? Cpus { get; set; }
        /// <summary>RFC 3339 creation timestamp.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Disk size in gigabytes.</summary>
        public int? DiskSizeGb { get; set; }
        /// <summary>Connection endpoints. Populated once the cluster is ready.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterEndpointsComposed? Endpoints { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterEndpointsComposed Endpoints { get; set; }
#endif
        /// <summary>Cluster ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Memory per node in megabytes.</summary>
        public int? MemoryMb { get; set; }
        /// <summary>Cluster name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The organization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.OrganizationRef? Organization { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.OrganizationRef Organization { get; set; }
#endif
        /// <summary>Postgres major version.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPgMajorVersion? PgMajorVersion { get; set; }
        /// <summary>Plan slug.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPlan? Plan { get; set; }
        /// <summary>Whether PostGIS support is enabled.</summary>
        public bool? PostgisEnabled { get; set; }
        /// <summary>Fly region code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>Number of replicas.</summary>
        public int? Replicas { get; set; }
        /// <summary>Current lifecycle status.</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresCluster"/> and sets the default values.
        /// </summary>
        public PostgresCluster()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresCluster"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresCluster CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresCluster();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attached_apps", n => { AttachedApps = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresAttachedApp>(global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresAttachedApp.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cpu_kind", n => { CpuKind = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterCpuKind>(); } },
                { "cpus", n => { Cpus = n.GetIntValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "disk_size_gb", n => { DiskSizeGb = n.GetIntValue(); } },
                { "endpoints", n => { Endpoints = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterEndpointsComposed>(global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterEndpointsComposed.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "memory_mb", n => { MemoryMb = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrganizationRef>(global::Soenneker.Fly.Machines.OpenApiClient.Models.OrganizationRef.CreateFromDiscriminatorValue); } },
                { "pg_major_version", n => { PgMajorVersion = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPgMajorVersion>(); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPlan>(); } },
                { "postgis_enabled", n => { PostgisEnabled = n.GetBoolValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "replicas", n => { Replicas = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresAttachedApp>("attached_apps", AttachedApps);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterCpuKind>("cpu_kind", CpuKind);
            writer.WriteIntValue("cpus", Cpus);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteIntValue("disk_size_gb", DiskSizeGb);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterEndpointsComposed>("endpoints", Endpoints);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("memory_mb", MemoryMb);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.OrganizationRef>("organization", Organization);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPgMajorVersion>("pg_major_version", PgMajorVersion);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterPlan>("plan", Plan);
            writer.WriteBoolValue("postgis_enabled", PostgisEnabled);
            writer.WriteStringValue("region", Region);
            writer.WriteIntValue("replicas", Replicas);
            writer.WriteEnumValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresClusterStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
