// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostgresActiveQuery : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Application connected to the backend.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationName { get; set; }
#nullable restore
#else
        public string ApplicationName { get; set; }
#endif
        /// <summary>Client address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Client { get; set; }
#nullable restore
#else
        public string Client { get; set; }
#endif
        /// <summary>Database name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Database { get; set; }
#nullable restore
#else
        public string Database { get; set; }
#endif
        /// <summary>Query duration in seconds.</summary>
        public double? DurationSeconds { get; set; }
        /// <summary>Process ID of the backend running the query.</summary>
        public int? Pid { get; set; }
        /// <summary>Full query text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Current backend state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>Time spent in the current state, in seconds.</summary>
        public double? StateDurationSeconds { get; set; }
        /// <summary>User running the query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>Event the backend is waiting for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WaitEvent { get; set; }
#nullable restore
#else
        public string WaitEvent { get; set; }
#endif
        /// <summary>Type of event the backend is waiting for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WaitEventType { get; set; }
#nullable restore
#else
        public string WaitEventType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresActiveQuery"/> and sets the default values.
        /// </summary>
        public PostgresActiveQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresActiveQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresActiveQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.PostgresActiveQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "application_name", n => { ApplicationName = n.GetStringValue(); } },
                { "client", n => { Client = n.GetStringValue(); } },
                { "database", n => { Database = n.GetStringValue(); } },
                { "duration_seconds", n => { DurationSeconds = n.GetDoubleValue(); } },
                { "pid", n => { Pid = n.GetIntValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "state_duration_seconds", n => { StateDurationSeconds = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
                { "wait_event", n => { WaitEvent = n.GetStringValue(); } },
                { "wait_event_type", n => { WaitEventType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("application_name", ApplicationName);
            writer.WriteStringValue("client", Client);
            writer.WriteStringValue("database", Database);
            writer.WriteDoubleValue("duration_seconds", DurationSeconds);
            writer.WriteIntValue("pid", Pid);
            writer.WriteStringValue("query", Query);
            writer.WriteStringValue("state", State);
            writer.WriteDoubleValue("state_duration_seconds", StateDurationSeconds);
            writer.WriteStringValue("user", User);
            writer.WriteStringValue("wait_event", WaitEvent);
            writer.WriteStringValue("wait_event_type", WaitEventType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
