// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProcessStat : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The command property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>The cpu property</summary>
        public int? Cpu { get; set; }
        /// <summary>The directory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Directory { get; set; }
#nullable restore
#else
        public string Directory { get; set; }
#endif
        /// <summary>The listen_sockets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.ListenSocket>? ListenSockets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fly.Machines.OpenApiClient.Models.ListenSocket> ListenSockets { get; set; }
#endif
        /// <summary>The pid property</summary>
        public int? Pid { get; set; }
        /// <summary>The rss property</summary>
        public int? Rss { get; set; }
        /// <summary>The rtime property</summary>
        public int? Rtime { get; set; }
        /// <summary>The stime property</summary>
        public int? Stime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.ProcessStat"/> and sets the default values.
        /// </summary>
        public ProcessStat()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.ProcessStat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.ProcessStat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.ProcessStat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "command", n => { Command = n.GetStringValue(); } },
                { "cpu", n => { Cpu = n.GetIntValue(); } },
                { "directory", n => { Directory = n.GetStringValue(); } },
                { "listen_sockets", n => { ListenSockets = n.GetCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.ListenSocket>(global::Soenneker.Fly.Machines.OpenApiClient.Models.ListenSocket.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pid", n => { Pid = n.GetIntValue(); } },
                { "rss", n => { Rss = n.GetIntValue(); } },
                { "rtime", n => { Rtime = n.GetIntValue(); } },
                { "stime", n => { Stime = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("command", Command);
            writer.WriteIntValue("cpu", Cpu);
            writer.WriteStringValue("directory", Directory);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fly.Machines.OpenApiClient.Models.ListenSocket>("listen_sockets", ListenSockets);
            writer.WriteIntValue("pid", Pid);
            writer.WriteIntValue("rss", Rss);
            writer.WriteIntValue("rtime", Rtime);
            writer.WriteIntValue("stime", Stime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
