// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SignalRequest_signal
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIGABRT")]
        #pragma warning disable CS1591
        SIGABRT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGALRM")]
        #pragma warning disable CS1591
        SIGALRM,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGFPE")]
        #pragma warning disable CS1591
        SIGFPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGHUP")]
        #pragma warning disable CS1591
        SIGHUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGILL")]
        #pragma warning disable CS1591
        SIGILL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGINT")]
        #pragma warning disable CS1591
        SIGINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGKILL")]
        #pragma warning disable CS1591
        SIGKILL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGPIPE")]
        #pragma warning disable CS1591
        SIGPIPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGQUIT")]
        #pragma warning disable CS1591
        SIGQUIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGSEGV")]
        #pragma warning disable CS1591
        SIGSEGV,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGTERM")]
        #pragma warning disable CS1591
        SIGTERM,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGTRAP")]
        #pragma warning disable CS1591
        SIGTRAP,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR1")]
        #pragma warning disable CS1591
        SIGUSR1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR2")]
        #pragma warning disable CS1591
        SIGUSR2,
        #pragma warning restore CS1591
    }
}
