// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SignalRequestSignal
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIGABRT")]
        #pragma warning disable CS1591
        Sigabrt,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGALRM")]
        #pragma warning disable CS1591
        Sigalrm,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGFPE")]
        #pragma warning disable CS1591
        Sigfpe,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGHUP")]
        #pragma warning disable CS1591
        Sighup,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGILL")]
        #pragma warning disable CS1591
        Sigill,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGINT")]
        #pragma warning disable CS1591
        Sigint,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGKILL")]
        #pragma warning disable CS1591
        Sigkill,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGPIPE")]
        #pragma warning disable CS1591
        Sigpipe,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGQUIT")]
        #pragma warning disable CS1591
        Sigquit,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGSEGV")]
        #pragma warning disable CS1591
        Sigsegv,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGTERM")]
        #pragma warning disable CS1591
        Sigterm,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGTRAP")]
        #pragma warning disable CS1591
        Sigtrap,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR1")]
        #pragma warning disable CS1591
        Sigusr1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR2")]
        #pragma warning disable CS1591
        Sigusr2,
        #pragma warning restore CS1591
    }
}
