// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StopRequest_signal
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SIGHUP")]
        #pragma warning disable CS1591
        SIGHUP,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGINT")]
        #pragma warning disable CS1591
        SIGINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGQUIT")]
        #pragma warning disable CS1591
        SIGQUIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGKILL")]
        #pragma warning disable CS1591
        SIGKILL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR1")]
        #pragma warning disable CS1591
        SIGUSR1,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGUSR2")]
        #pragma warning disable CS1591
        SIGUSR2,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGTERM")]
        #pragma warning disable CS1591
        SIGTERM,
        #pragma warning restore CS1591
    }
}
