// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    /// <summary>New role for the user.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdatePostgresUserRoleRequestRole
    {
        [EnumMember(Value = "schema_admin")]
        #pragma warning disable CS1591
        SchemaAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "writer")]
        #pragma warning disable CS1591
        Writer,
        #pragma warning restore CS1591
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
    }
}
