// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateMachineRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object defining the Machine configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequestConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequestConfig Config { get; set; }
#endif
        /// <summary>The current_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentVersion { get; set; }
#nullable restore
#else
        public string CurrentVersion { get; set; }
#endif
        /// <summary>The lease_ttl property</summary>
        public int? LeaseTtl { get; set; }
        /// <summary>The min_secrets_version property</summary>
        public int? MinSecretsVersion { get; set; }
        /// <summary>Unique name for this Machine. If omitted, one is generated for you</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The skip_launch property</summary>
        public bool? SkipLaunch { get; set; }
        /// <summary>The skip_secrets property</summary>
        public bool? SkipSecrets { get; set; }
        /// <summary>The skip_service_registration property</summary>
        public bool? SkipServiceRegistration { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequest"/> and sets the default values.
        /// </summary>
        public UpdateMachineRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequestConfig>(global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequestConfig.CreateFromDiscriminatorValue); } },
                { "current_version", n => { CurrentVersion = n.GetStringValue(); } },
                { "lease_ttl", n => { LeaseTtl = n.GetIntValue(); } },
                { "min_secrets_version", n => { MinSecretsVersion = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "skip_launch", n => { SkipLaunch = n.GetBoolValue(); } },
                { "skip_secrets", n => { SkipSecrets = n.GetBoolValue(); } },
                { "skip_service_registration", n => { SkipServiceRegistration = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fly.Machines.OpenApiClient.Models.UpdateMachineRequestConfig>("config", Config);
            writer.WriteStringValue("current_version", CurrentVersion);
            writer.WriteIntValue("lease_ttl", LeaseTtl);
            writer.WriteIntValue("min_secrets_version", MinSecretsVersion);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("region", Region);
            writer.WriteBoolValue("skip_launch", SkipLaunch);
            writer.WriteBoolValue("skip_secrets", SkipSecrets);
            writer.WriteBoolValue("skip_service_registration", SkipServiceRegistration);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
