// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Active;
using Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Slow;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\postgres\{postgresClusterId}\queries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Active.ActiveRequestBuilder Active
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The slow property</summary>
        public global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Slow.SlowRequestBuilder Slow
        {
            get => new global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.Slow.SlowRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.QueriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/postgres/{postgresClusterId}/queries", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fly.Machines.OpenApiClient.V1.Postgres.Item.Queries.QueriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/postgres/{postgresClusterId}/queries", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
